### ISSUE TITLE
Program crashes on first move

### ISSUE THREAD

**Issue by emilnt1** [emilnt1/SolitareImageRecognition#10]
Traceback (most recent call last):
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\Ui.py", line 240, in <module>
    main()
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\Ui.py", line 223, in main
    instruction = treeSearchBackTracking(currBoard)
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\AI\Algorithm.py", line 8, in treeSearchBackTracking
    priorityQueue.extend(analyse_moves(node))
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\AI\Algorithm.py", line 30, in analyse_moves
    moves.extend(columnToFoundation(node.board))
AttributeError: 'Board' object has no attribute 'board'

Board printed:
![image](https://user-images.githubusercontent.com/23736406/172858931-8bab9c8d-0786-4a39-a819-6c8ae2b1af4d.png)
 Board irl:
![image](https://user-images.githubusercontent.com/23736406/172859021-adc4b33c-ece8-412e-a36b-d74428186420.png)

**Comment by Machnuud** [comment]
Works or the feature isn't relevant anymore
