### ISSUE TITLE
Program crashed when make a draw from drawpile

### ISSUE THREAD

**Issue by emilnt1** [emilnt1/SolitareImageRecognition#6]
Traceback dump.
Traceback (most recent call last):
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\Ui.py", line 238, in <module>
    main()
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\Ui.py", line 222, in main  
    instruction = nextMove(currBoard)
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\AI\AI.py", line 38, in nextMove
    curr_result = move(board)
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\AI\AI.py", line 116, in putColumn
    cardsLeftDeckDrawPile -= 1
UnboundLocalError: local variable 'cardsLeftDeckDrawPile' referenced before assignment

**State of the game:**
![image](https://user-images.githubusercontent.com/23736406/172809122-99cf7e5f-d7d1-48c3-8693-c9a60ce32357.png)

![image](https://user-images.githubusercontent.com/23736406/172809396-d1fba734-e4bd-4722-85af-a886c0a094cc.png)

**Comment by emilnt1** [comment]
This bug is able to be replicated with the deck from "Mellem_kabale_1"
