### ISSUE TITLE
When the wrong card is taken to foundation in the end game, the program crashes

### ISSUE THREAD

**Issue by emilnt1** [emilnt1/SolitareImageRecognition#8]
Traceback:

Traceback (most recent call last):
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\Ui.py", line 238, in <module>
    main()
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\Ui.py", line 222, in main
    instruction = nextMove(currBoard)
  File "c:\Users\emilb\Documents\SolitareImageRecognition\SolitareImageRecognition-1\AI\AI.py", line 41, in nextMove
    if ( len(curr_result) != 0):
TypeError: object of type 'NoneType' has no len()

State of the game:
![image](https://user-images.githubusercontent.com/23736406/172822326-652b7b95-e9e2-4983-a47a-56735e924655.png)

**Comment by ArmandasRokas** [comment]
Done. ready for test

**Comment by Machnuud** [comment]
Hurray it is very fixed
